name: bc-scanner-backend
services:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
    deploy_on_push: true
  run_command: gunicorn --worker-tmp-dir /dev/shm core.wsgi
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /admin/
  env:
  - key: DJANGO_SETTINGS_MODULE
    value: core.production_settings
  - key: SECRET_KEY
    type: SECRET
    value: your-secret-key-here
  - key: DEBUG
    value: "False"
  - key: DATABASE_URL
    type: SECRET
    value: ${db.DATABASE_URL}

databases:
- name: db
  engine: PG
  version: "13"
  size: basic
  num_nodes: 1

static_sites: [] 