# Generated by Django 5.0.2 on 2025-06-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable or disable automated email notifications')),
                ('sender_email', models.EmailField(help_text='Email address to send notifications from', max_length=255)),
                ('sender_password', models.CharField(help_text='App password or email account password', max_length=255)),
                ('recipient_email', models.EmailField(help_text='Email address to receive notifications', max_length=255)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname', max_length=255)),
                ('smtp_port', models.CharField(default='587', help_text='SMTP server port', max_length=10)),
                ('email_subject', models.CharField(default='New Business Card Scanned', help_text='Subject line for automated emails', max_length=255)),
                ('email_template', models.TextField(default='A new business card has been scanned and added to your collection.', help_text='Email message template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
    ]
