# Generated by Django 5.0.2 on 2025-06-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_emailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
