# Generated by Django 4.2.7 on 2025-06-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_businesscard_deleted_at_businesscard_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular Business Card'), ('qr_business_card', 'QR Code Business Card')], default='regular', max_length=20),
        ),
    ]
