# Generated by Django 4.2.7 on 2025-06-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_businesscard_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='businesscard',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='back_side_text',
            field=models.TextField(blank=True, help_text='Raw OCR text from back side', null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='company_full_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='email_secondary',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='front_side_text',
            field=models.TextField(blank=True, help_text='Raw OCR text from front side', null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='business_cards/back/'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='image_front',
            field=models.ImageField(blank=True, null=True, upload_to='business_cards/front/'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the data has been manually verified'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='job_title_secondary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='landline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='mobile_secondary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Whether this card needs manual review'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='primary_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='processing_time',
            field=models.FloatField(default=0.0, help_text='Time taken to process in seconds'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='qr_code_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='scan_confidence',
            field=models.FloatField(default=0.0, help_text='OCR confidence score (0-100)'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='scan_method',
            field=models.CharField(blank=True, help_text='OCR method used', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='secondary_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='skype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='specialization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='street_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='website_secondary',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular Business Card'), ('qr_business_card', 'QR Code Business Card'), ('dual_side', 'Dual-Side Business Card')], default='regular', max_length=20),
        ),
        migrations.AddIndex(
            model_name='businesscard',
            index=models.Index(fields=['company'], name='scanner_bus_company_274374_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscard',
            index=models.Index(fields=['name'], name='scanner_bus_name_502a74_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscard',
            index=models.Index(fields=['email'], name='scanner_bus_email_87fae5_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscard',
            index=models.Index(fields=['created_at'], name='scanner_bus_created_adfa55_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscard',
            index=models.Index(fields=['is_deleted'], name='scanner_bus_is_dele_cba6d7_idx'),
        ),
    ]
